In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv('customer_shopping_behavior.csv')

df = df.rename(columns={
    'Purchase Amount (USD)': 'Purchase Amount',
    'Review Rating': 'Review Rating',
    'Previous Purchases': 'Previous Purchases'
})
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount,Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly


In [3]:
ages      = df['Age'].to_numpy()
purchases = df['Purchase Amount'].to_numpy()
ratings   = df['Review Rating'].dropna().to_numpy()
prev_pur  = df['Previous Purchases'].to_numpy()

print( 'Data extracted as NumPy arrays')
print('Ages array shape:', ages.shape)
print('First 5 ages:', ages[:5])

Data extracted as NumPy arrays
Ages array shape: (3900,)
First 5 ages: [55 19 50 21 45]


In [6]:
arr1 = np.array([10, 20, 30, 40, 50])          
zeros = np.zeros(5)                            
ones  = np.ones(5)                              
rng   = np.arange(1, 11)                        
lin   = np.linspace(0, 100, 5)                  

print('Basic array  :', arr1)
print('Zeros array  :', zeros)
print('Ones array   :', ones)
print('Range 1-10   :', rng)
print('Linspace 0-100:', lin)

Basic array  : [10 20 30 40 50]
Zeros array  : [0. 0. 0. 0. 0.]
Ones array   : [1. 1. 1. 1. 1.]
Range 1-10   : [ 1  2  3  4  5  6  7  8  9 10]
Linspace 0-100: [  0.  25.  50.  75. 100.]


In [7]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print('2D Matrix:')
print(matrix)
print('Shape:', matrix.shape)  
print('Dimensions:', matrix.ndim)

2D Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2


In [8]:
print('First customer age       :', ages[0])
print('Last customer age        :', ages[-1])
print('First 5 ages             :', ages[:5])
print('Ages from index 10 to 14 :', ages[10:15])
print('Every 100th age          :', ages[::100])

First customer age       : 55
Last customer age        : 52
First 5 ages             : [55 19 50 21 45]
Ages from index 10 to 14 : [53 30 61 65 64]
Every 100th age          : [55 62 25 29 39 36 22 57 32 54 43 50 27 67 36 63 20 62 22 65 26 68 60 18
 43 59 21 22 70 41 57 50 67 26 39 38 67 28 19]


In [9]:
print('Full matrix:')
print(matrix)
print('\nRow 0 (first row)     :', matrix[0])
print('Column 1 (2nd column) :', matrix[:, 1])
print('Element at row1,col2  :', matrix[1, 2])
print('Top-left 2x2 block    :')
print(matrix[0:2, 0:2])

Full matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Row 0 (first row)     : [1 2 3]
Column 1 (2nd column) : [2 5 8]
Element at row1,col2  : 6
Top-left 2x2 block    :
[[1 2]
 [4 5]]


In [10]:
mask = ages > 50
senior_ages = ages[mask]
print('Customers over 50:', len(senior_ages))
print('Their ages:', senior_ages[:10])

Customers over 50: 1476
Their ages: [55 63 57 53 61 65 64 64 53 52]


In [14]:
mask = ages > 50
senior_ages = ages[mask]
len(senior_ages)
senior_ages[:5]

array([55, 63, 57, 53, 61])

In [6]:
# converting dollars to rupees
purchases_inr = purchases * 83
print('First 5 purchases in USD:', purchases[:5])
print('First 5 purchases in INR:', purchases_inr[:5])

First 5 purchases in USD: [53 64 73 90 49]
First 5 purchases in INR: [4399 5312 6059 7470 4067]


In [7]:
print('Square root of first 5 purchases:', np.sqrt(purchases[:5]).round(2))
print('Log of first 5 purchases        :', np.log(purchases[:5]).round(2))
print('Absolute values (no negatives)  :', np.abs(purchases[:5]))

Square root of first 5 purchases: [7.28 8.   8.54 9.49 7.  ]
Log of first 5 purchases        : [3.97 4.16 4.29 4.5  3.89]
Absolute values (no negatives)  : [53 64 73 90 49]


In [8]:
# Apply a 10% discount to all purchases
discounted = purchases * 0.90
print('Original prices  :', purchases[:5])
print('After 10% discount:', discounted[:5].round(2))

Original prices  : [53 64 73 90 49]
After 10% discount: [47.7 57.6 65.7 81.  44.1]


In [9]:
print('--- Purchase Amount Statistics ---')
print(f'Mean (Average)   : ${np.mean(purchases):.2f}')
print(f'Median           : ${np.median(purchases):.2f}')
print(f'Std Deviation    : ${np.std(purchases):.2f}')
print(f'Variance         : {np.var(purchases):.2f}')
print(f'Minimum          : ${np.min(purchases)}')
print(f'Maximum          : ${np.max(purchases)}')
print(f'Total Sum        : ${np.sum(purchases):,}')

--- Purchase Amount Statistics ---
Mean (Average)   : $59.76
Median           : $60.00
Std Deviation    : $23.68
Variance         : 560.85
Minimum          : $20
Maximum          : $100
Total Sum        : $233,081


In [10]:
print(f'25th percentile (Q1) : ${np.percentile(purchases, 25)}')
print(f'50th percentile (Q2) : ${np.percentile(purchases, 50)}')
print(f'75th percentile (Q3) : ${np.percentile(purchases, 75)}')
print(f'90th percentile      : ${np.percentile(purchases, 90)}')

25th percentile (Q1) : $39.0
50th percentile (Q2) : $60.0
75th percentile (Q3) : $81.0
90th percentile      : $93.0


In [11]:
print('Index of highest purchase:', np.argmax(purchases))
print('Highest purchase amount  :', np.max(purchases))
print('Index of lowest purchase :', np.argmin(purchases))
print('Lowest purchase amount   :', np.min(purchases))

Index of highest purchase: 42
Highest purchase amount  : 100
Index of lowest purchase : 5
Lowest purchase amount   : 20


In [5]:
unique_ages, counts = np.unique(ages, return_counts=True)
print('Unique ages and how many customers per age:')
for age, count in zip(unique_ages[:10], counts[:10]):
    print(f'  Age {age}: {count} customers')

Unique ages and how many customers per age:
  Age 18: 69 customers
  Age 19: 81 customers
  Age 20: 62 customers
  Age 21: 69 customers
  Age 22: 66 customers
  Age 23: 71 customers
  Age 24: 68 customers
  Age 25: 85 customers
  Age 26: 69 customers
  Age 27: 83 customers


In [6]:
clv = purchases * prev_pur

print('--- Customer Lifetime Value (CLV) ---')
print(f'Average CLV       : ${np.mean(clv):,.2f}')
print(f'Highest CLV       : ${np.max(clv):,}')
print(f'Lowest CLV        : ${np.min(clv):,}')
print(f'Top 10% CLV cutoff: ${np.percentile(clv, 90):,.0f}')

# How many customers are in the top 10% by CLV?
top_clv_mask = clv >= np.percentile(clv, 90)
print(f'\nTop 10% customers : {np.sum(top_clv_mask)} customers')

--- Customer Lifetime Value (CLV) ---
Average CLV       : $1,517.88
Highest CLV       : $5,000
Lowest CLV        : $21
Top 10% CLV cutoff: $3,196

Top 10% customers : 390 customers
